theme = "no-style-please"

base_url = "https://fart-game.kuviman.com"

title = "Getting Farted On"
description = "Foddian Game"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true

[extra]
