name: CI
on: push
env:
  CONNECT: wss://gfo.kuviman.com

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: kuviman/geng
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cargo geng build --release --target wasm32-unknown-unknown
      - name: Upload artifacts (web)
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: target/geng
      - run: cargo geng build --release
      - name: Upload artifacts (linux)
        uses: actions/upload-artifact@v2
        with:
          name: linux
          path: target/geng

  deploy:
    name: Deploy
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: main
      url: https://kuviman.itch.io/getting-farted-on
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Upload itch.io (Web)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: getting-farted-on
          ITCH_USER: kuviman
          PACKAGE: web
      - name: Copy server files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: linux
          target: getting-farted-on
      - name: Deploy server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: systemctl --user restart gfo

  deploy-dev:
    name: Deploy (Dev)
    if: github.ref == 'refs/heads/dev' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: dev
      url: https://kuviman.github.io/getting-farted-on/dev/?connect=singleplayer
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web
          destination_dir: dev
